FORMAT: 1A
HOST: http://iot-bath-light-sensor.herokuapp.com/webapi

# bath-light-sensor

This is API enables the user to check whether a bathroom light in a given house and room is on or not. 

## Single Light Status [/status/house/house_id/room/room_id]

### Single Light Status[GET]

Returns the status of the light in a single bathroom.

+ Parameters
    + house_id (number) - ID of the given house
    + room_id (number) - ID of the given room
    
+ Response 200 (application/json)

        {
            "house_id": "3",
            "room_id": "5",
            "is_light_on": "true",
            "light_switch_time": "2016-06-11T22:13:06.460Z"
        }

## All Rooms Status In a House [/status/house/house_id]

### All Rooms Status[GET]

Returns the status of all the lights in a single house.

+ Parameters 
    + house_id (number) - ID of the given house
    
+ Response 200 (application/json)

        {
            "house_id": "3",
            "rooms":
                [  
                    {
                        "house_id": "3",
                        "room_id": "1",
                        "is_light_on": "true",
                        "light_switch_time": "2016-06-11T22:11:45.513Z"
                    },
                    {
                        "house_id": "3",
                        "room_id": "2",
                        "is_light_on": "false",
                        "light_switch_time": "2016-06-11T22:14:51.073Z"
                    },
                    {
                        "house_id": "3",
                        "room_id": "3",
                        "is_light_on": "false",
                        "light_switch_time": "2016-06-11T22:15:07.220Z"
                    }
                ]
        }
        

## All Rooms Status In All Houses [/status/]

### All Houses Status[GET]

Returns the status of all of the lights in all of the houses.

+ Response 200 (application/json)

        {   
            "houses":
                [   
                    {
                        "house_id": "1",
                        "rooms":
                            [  
                                {
                                    "house_id": "1",
                                    "room_id": "1",
                                    "is_light_on": "true",
                                    "light_switch_time": "2016-06-11T22:13:16.673Z"
                                },
                                {
                                    "house_id": "1",
                                    "room_id": "2",
                                    "is_light_on": "false",
                                    "light_switch_time": "2016-06-11T22:10:53.490Z"
                                }
                            ]
                    },
                    {
                        "house_id": "2",
                        "rooms":
                            [  
                                {
                                    "house_id": "2",
                                    "room_id": "1",
                                    "is_light_on": "false",
                                    "light_switch_time": "2016-06-11T22:25:07.224Z"
                                },
                                {
                                    "house_id": "2",
                                    "room_id": "2",
                                    "is_light_on": "true",
                                    "light_switch_time": "2016-06-11T22:45:00.056Z"
                                },
                                {
                                    "house_id": "2",
                                    "room_id": "3",
                                    "is_light_on": "false",
                                    "light_switch_time": "2016-06-11T22:00:59.304Z"
                                }
                            ]
                    },
                    {
                        "house_id": "3",
                        "rooms":
                            [
                                {
                                    "house_id": "3",
                                    "room_id": "1",
                                    "is_light_on": "true",
                                    "light_switch_time": "2016-06-11T22:15:07.220Z"
                                }
                            ]    
                    }    
                ]
        }
        
## Single Room History [/history/house/house_id/room/room_id]

### Room History[GET]

Returns the history of light switches in a single bathroom.

+ Parameters
    + house_id (number) - ID of the given house
    + room_id (number) - ID of the given room

+ Response 200 (application/json)

        {
            "house_id": "4",
            "room_id": "1",
            "history":
                [
                    {
                        "light_on": "true",
                        "light_switch_time": "2016-06-11T22:15:07.220Z"
                    },
                    {
                        "light_on": "false",
                        "light_switch_time": "2016-06-11T22:15:34.513Z"
                    },
                    {
                        "light_on": "true",
                        "light_switch_time": "2016-06-11T22:17:23.410Z"
                    }
                ]
        }
        
## All Rooms History In A House [/history/house/house_id/]

### All Rooms History[GET]

Returns the history of light switches in all bathrooms of a given house.

+ Parameters
    + house_id (number) - ID of the given house

+ Response 200 (application/json)

        {
            "house_id": "2",
            "rooms":
                [
                    {
                        "house_id": "2",
                        "room_id": "1",
                        "history":
                            [
                                {
                                    "light_on": "true",
                                    "light_switch_time": "2016-06-11T22:15:07.220Z"
                                },
                                {
                                    "light_on": "false",
                                    "light_switch_time": "2016-06-11T22:15:34.513Z"
                                }
                            ]
                    },
                    {
                        "house_id": "2",
                        "room_id": "2",
                        "history":
                            [
                                {
                                    "light_on": "true",
                                    "light_switch_time": "2016-06-11T22:03:35.046Z"
                                }
                            ]
                    }
                ]
        }
        
## All Rooms History In All Houses [/history/]

### All Houses History[GET]

Returns the history of light switches in all houses.

+ Response 200 (application/json)

        {
            "houses":
                [
                    {
                        "house_id": "1",
                        "rooms":
                            [
                                {
                                    "house_id": "1",
                                    "room_id": "1",
                                    "history":
                                        [
                                            {
                                                "light_on": "true",
                                                "light_switch_time": "2016-06-11T22:00:00.000Z"
                                            },
                                            {
                                                "light_on": "false",
                                                "light_switch_time": "2016-06-11T22:00:05.000Z"
                                            },
                                            {
                                                "light_on": "true",
                                                "light_switch_time": "2016-06-11T22:00:10.000Z"
                                            }
                                        ]
                                }
                            ]
                    {
                        "house_id": "2",
                        "rooms":
                            [
                                {
                                    "house_id": "2",
                                    "room_id": "1",
                                    "history":
                                        [
                                            {
                                                "light_on": "true",
                                                "light_switch_time": "2016-06-11T22:15:07.220Z"
                                            },
                                            {
                                                "light_on": "false",
                                                "light_switch_time": "2016-06-11T22:15:34.513Z"
                                            }
                                        ]
                                },
                                {
                                    "house_id": "2",
                                    "room_id": "2",
                                    "history":
                                        [
                                            {
                                                "light_on": "true",
                                                "light_switch_time": "2016-06-11T22:03:35.046Z"
                                            }
                                        ]
                                }
                            ]
                    }
                ]
        }
        
## Ping [/ping]

### Ping [GET]

Returnes status code `200` if server is responding.

+ Response 200