FORMAT: 1A
HOST: http://iot-bath-light-sensor.herokuapp.com/webapi

# bath-light-sensor

This is API enables the user to check whether a bathroom light in a given house is on or not. 

## Single Light Status [/status/house/{house_id}]

### Single Light Status[GET]

Returns the status of the light in a single bathroom. Also returns the house id and time of light status last change.

+ Parameters
    + house_id (number) - ID of the given house
    
+ Response 200 (application/json)

        {
            "houseId": "3",
            "status": "true",
            "time": "2016-06-11T22:13:06.460Z"
        }

## All Houses Status [/status]

### All Houses Status[GET]

Returns the status of all of the lights in all houses.

+ Response 200 (application/json)

        [
            {
                "houseId":"1",
                "time": "2016-06-11T22:15:07.220Z",
                "status":"true"
            },
            {
                "houseId":"2",
                "time": "2016-06-11T22:15:34.513Z",
                "status":"false"
            },
            {
                "houseId":"3",
                "time": "2016-06-11T22:17:23.410Z",
                "status":"true"
            }
        ]

## Ping [/ping]

### Ping [GET]

Returnes status code `200` if server is responding.

+ Response 200